'use client';
import {useState,type FormEvent} from 'react';
import {api,directUpload,FilePlayer,input,button,downloadText} from './shared';
import {campaignBlockers,contractBlockers,type Campaign} from '@/lib/collaborations/contracts';
async function cropPreview(id:string,start:number){
 const {url}=await api(`/api/admin/collaborations?kind=file&id=${id}&field=demo_path`);
 const res=await fetch(url);if(!res.ok)throw new Error('No se pudo abrir el demo.');
 const ctx=new AudioContext();let decoded:AudioBuffer;try{decoded=await ctx.decodeAudioData(await res.arrayBuffer());}finally{await ctx.close();}
 const seconds=Math.min(30,decoded.duration-start);if(!Number.isFinite(start)||start<0||seconds<10)throw new Error('El fragmento necesita al menos 10 segundos y máximo 30.');
 const frames=Math.floor(seconds*22050),offline=new OfflineAudioContext(1,frames,22050),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start(0,start,seconds);const rendered=await offline.startRendering();const pcm=rendered.getChannelData(0);let peak=0;for(const v of pcm)peak=Math.max(peak,Math.abs(v));const gain=peak>0?.89/peak:1;
 const bytes=new ArrayBuffer(44+frames*2),v=new DataView(bytes);const word=(at:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(at+i,s.charCodeAt(i));};word(0,'RIFF');v.setUint32(4,36+frames*2,true);word(8,'WAVE');word(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,22050,true);v.setUint32(28,44100,true);v.setUint16(32,2,true);v.setUint16(34,16,true);word(36,'data');v.setUint32(40,frames*2,true);for(let i=0;i<frames;i++)v.setInt16(44+i*2,Math.round(Math.max(-1,Math.min(1,pcm[i]*gain))*32767),true);return new Blob([bytes],{type:'audio/wav'});
}
function SplitEditor({value,onChange,locked}:{value:any;onChange:(v:any)=>void;locked:boolean}){
 function set(key:string,v:any){onChange({...value,[key]:v});}
 const master=value.master||[{name:'EM Records',email:'',side:'em',percent:50},{name:'',email:'',side:'artist',percent:50}];
 const composition=value.composition||[{name:'',pro:'BMI',ipi:'',publisher:'PUBLISHING BY DGM MUSIC',side:'em',percent:50},{name:'',pro:'',ipi:'',publisher:'',side:'artist',percent:50}];
 return <fieldset disabled={locked} className="space-y-5"><legend className="text-lg text-white">Beneficiarios y anexos</legend>{locked?<p className="text-xs text-gold">Bloqueados: acuerdo emitido.</p>:null}
 {[['master','Master',master,['name','email','side','percent']],['composition','Composición',composition,['name','pro','ipi','publisher','side','percent']]].map(([key,label,rows,fields]:any)=><div key={key}><h4 className="mb-2 text-sm text-gold">{label}</h4>{rows.map((row:any,i:number)=><div key={i} className="mb-3 grid gap-2 sm:grid-cols-3">{fields.map((field:string)=><label className="text-xs text-white/55" key={field}>{({name:'Nombre legal',email:'Correo de cobro',side:'Lado',percent:'Porcentaje',pro:'PRO',ipi:'IPI / CAE',publisher:'Publishing'} as any)[field]}{field==='side'?<select className={input} value={row[field]||'em'} onChange={e=>set(key,rows.map((x:any,n:number)=>n===i?{...x,[field]:e.target.value}:x))}><option value="em">EM / RBELD</option><option value="artist">Artista</option></select>:<input type={field==='percent'?'number':field==='email'?'email':'text'} min={0} max={100} step="0.01" className={input} value={row[field]??''} onChange={e=>set(key,rows.map((x:any,n:number)=>n===i?{...x,[field]:field==='percent'?Number(e.target.value):e.target.value}:x))}/>}</label>)}<button type="button" className="text-xs text-red-300" onClick={()=>set(key,rows.filter((_:any,n:number)=>n!==i))}>Quitar beneficiario</button></div>)}<button type="button" className={button} onClick={()=>set(key,[...rows,{name:'',side:'em',percent:0}])}>Agregar beneficiario</button></div>)}
 {([['delivery_date','Fecha de entrega','date'],['release_deadline','Fecha límite de lanzamiento','date'],['governing_law','Ley, jurisdicción y procedimiento de disputa','text'],['account_costs','Quién cubre cuentas de cobro y retiros','text']] as const).map(([key,label,type])=><label className="block text-sm text-white/65" key={key}>{label}<input className={input+' mt-2'} type={type} value={value[key]||''} onChange={e=>set(key,e.target.value)}/></label>)}
 </fieldset>;
}
function SubmissionCard({s,c,run}:{s:any;c:Campaign;run:(fn:()=>Promise<void>)=>Promise<void>}){
 const [review,setReview]=useState({status:s.status,rights_verified:s.rights_verified,notes:s.notes,splits:s.splits,production_checklist:s.production_checklist});const [start,setStart]=useState(0);
 const blockers=contractBlockers(c,{...s,...review});
 return <article className="rounded-3xl border border-white/15 bg-white/[.025] p-6"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-display text-2xl text-white">{s.track_title}</h3><p className="text-sm text-white/60">{s.artist_name} · {s.email}</p><p className="mt-1 text-xs text-gold">{s.status} · {s.votes} votos · {s.beat_source==='catalog'?'Beat de catálogo':'Beat externo'}</p></div><p className="text-xs text-white/40">{new Date(s.created_at).toLocaleString()}</p></div>
 <div className="mt-4"><FilePlayer id={s.id} admin/></div><details className="mt-5"><summary className="cursor-pointer text-gold">Expediente, preview y derechos</summary><div className="mt-4 space-y-4"><p className="text-sm text-white/65">Nombre legal: {s.legal_name}. PRO: {s.pro}. IPI: {s.ipi}. Publisher: {s.publisher}. {s.beat_rights}</p><p className="text-sm text-white/65">{s.message}</p>{s.document_path?<FilePlayer id={s.id} admin field="document_path"/>:<p className="text-sm text-amber-300">No hay documento de derechos adjunto.</p>}<details><summary className="text-sm text-white/65">Aceptación original</summary><pre className="max-h-48 overflow-auto whitespace-pre-wrap text-xs text-white/55">{JSON.stringify(s.submission_terms,null,2)}</pre></details>
 <div className="flex flex-wrap gap-3"><label className="text-sm text-white/65">Inicio del preview (segundos)<input type="number" min={0} className={input} value={start} onChange={e=>setStart(Number(e.target.value))}/></label><button type="button" className={button} onClick={()=>run(async()=>{const f=await cropPreview(s.id,start);const t=await api('/api/admin/collaborations',{action:'upload',id:s.id,kind:'preview',bytes:f.size});await directUpload(f,t);await api('/api/admin/collaborations',{action:'complete',id:s.id,uploadId:t.uploadId});})}>Crear preview de hasta 30 s</button></div>{s.preview_path?<FilePlayer id={s.id} admin field="preview_path"/>:null}
 <label className="block text-sm text-white/65"><input type="checkbox" checked={review.rights_verified} onChange={e=>setReview({...review,rights_verified:e.target.checked})}/> Revisé titularidad, permisos, beat, samples y usos audiovisuales.</label><label className="block text-sm text-white/65">Estado<select className={input+' mt-2'} value={review.status} onChange={e=>setReview({...review,status:e.target.value})}>{['received','rights_pending','approved','selected','reserve','rejected','production','released'].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm text-white/65">Notas y evidencia<textarea className={input+' mt-2'} rows={3} value={review.notes} onChange={e=>setReview({...review,notes:e.target.value})}/></label>
 <SplitEditor value={review.splits} locked={s.contract_ready} onChange={splits=>setReview({...review,splits})}/>
 <h4 className="text-lg text-white">Producción y lanzamiento</h4>{[['legal_hold','Conservar por disputa o requerimiento legal'],['all_signatures','Todas las partes y titulares firmaron'],['audio','Audio final aprobado'],['art','Portada aprobada'],['credits','Créditos y metadata aprobados'],['pro_registration','Registros PRO verificados'],['mlc_registration','Registro mecánico / administrador verificado'],['distrokid_splits','Todos aceptaron sus Splits'],['distribution','Distribución e ISRC confirmados']].map(([key,label])=><label className="block text-sm text-white/65" key={key}><input type="checkbox" checked={!!review.production_checklist[key]} onChange={e=>setReview({...review,production_checklist:{...review.production_checklist,[key]:e.target.checked}})}/> {label}</label>)}<label className="block text-sm text-white/65">ISRC / referencia de distribución<input className={input} value={review.production_checklist.isrc||''} onChange={e=>setReview({...review,production_checklist:{...review.production_checklist,isrc:e.target.value}})}/></label>
 <button type="button" className={button} onClick={()=>run(async()=>{await api('/api/admin/collaborations',{action:'review',id:s.id,review});})}>Guardar revisión y anexos</button><p className="text-xs text-amber-200">Pendiente para contrato: {blockers.length?blockers.join(' · '):'Anexos completos; guarda antes de emitir.'}</p><button className={button} onClick={()=>run(async()=>{await api('/api/admin/collaborations',{action:'contract',id:s.id});})} disabled={s.contract_ready}>Emitir acuerdo al artista</button>
 {s.contract_text?<><button className={button} onClick={()=>downloadText(`${s.track_title}-acuerdo.txt`,s.contract_text)}>Descargar acuerdo</button><p className="text-xs text-white/60">Aceptación del artista: {s.contract_signature?s.contract_signature.accepted_at:'Pendiente'}</p></>:null}<label className="block text-sm text-white/65">Acuerdo PDF con todas las firmas (hasta 2 MB)<input type="file" accept="application/pdf" onChange={e=>{const f=e.target.files?.[0];if(f)run(async()=>{const t=await api('/api/admin/collaborations',{action:'upload',id:s.id,kind:'contract',bytes:f.size});await directUpload(f,t);await api('/api/admin/collaborations',{action:'complete',id:s.id,uploadId:t.uploadId});});}}/></label>{s.production_checklist.signed_contract?<FilePlayer id={s.id} admin field="signed_contract"/>:null}
 </div></details></article>;
}
export function AdminHub({initial}:{initial:any}){
 const [data,setData]=useState(initial),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[campaignId,setCampaignId]=useState(initial.campaigns[0]?.id||''),[filter,setFilter]=useState('all');
 const c:Campaign|undefined=data.campaigns.find((x:any)=>x.id===campaignId);
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();setData(await api('/api/admin/collaborations'));setMessage('Guardado.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function saveCampaign(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const x:any={};for(const k of ['title','description','project_artist','legal_entity','eligibility','promotion_commitment','status'])x[k]=f.get(k);for(const k of ['submissions_start','submissions_end','voting_start','voting_end'])x[k]=f.get(k)?new Date(String(f.get(k))).toISOString():null;x.max_submissions=Number(f.get('max_submissions'));x.legal_reviewed=f.get('legal_reviewed')==='on';await api('/api/admin/collaborations',{action:'campaign',id:c!.id,campaign:x});});}
 const songs=data.submissions.filter((s:any)=>s.campaign_id===campaignId);const ranked=[...songs].filter(s=>s.status==='approved').sort((a,b)=>b.votes-a.votes||a.created_at.localeCompare(b.created_at));
 function exportData(){const csv=['id,title,artist,status,votes,rights,contract',...songs.map((s:any)=>[s.id,s.track_title,s.artist_name,s.status,s.votes,s.rights_verified,!!s.contract_signature].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\n');downloadText('collaborations.csv',csv);}
 return <div className="space-y-7"><header><p className="text-xs uppercase tracking-[.2em] text-gold">A&R · derechos · producción</p><h1 className="mt-2 font-display text-4xl text-white">Collaborations</h1><p className="mt-3 text-white/60">Demos completos privados, previews separados y expedientes por canción.</p></header><div className="flex flex-wrap gap-3"><a className={button} href="/collaborations">Página pública</a><a className={button} href="/admin/demos">Demos generales</a><button className={button} onClick={exportData}>Exportar expedientes</button></div>{message?<p role="status" className="rounded-xl border border-gold/30 p-4 text-sm text-white">{message}</p>:null}{busy?<p className="text-sm text-gold">Procesando…</p>:null}
 <form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const r=await api('/api/admin/collaborations',{action:'create_campaign',title:f.get('title')});setCampaignId(r.id);});}}><input name="title" required maxLength={150} className={input+' max-w-sm'} placeholder="Nombre del próximo volumen" aria-label="Nueva convocatoria"/><button className={button} disabled={busy}>Crear convocatoria en borrador</button></form><div className="grid gap-3 sm:grid-cols-4">{[['Recibidos',songs.length],['Derechos pendientes',songs.filter((s:any)=>!s.rights_verified).length],['Listos para votar',songs.filter((s:any)=>s.status==='approved').length],['Aceptaciones pendientes',songs.filter((s:any)=>s.contract_ready&&!s.contract_signature).length]].map(([label,n])=><div className="rounded-2xl border border-white/15 p-4" key={String(label)}><p className="text-xs text-white/50">{label}</p><p className="mt-2 text-3xl text-white">{n}</p></div>)}</div>
 <select className={input} aria-label="Convocatoria" value={campaignId} onChange={e=>setCampaignId(e.target.value)}>{data.campaigns.map((x:any)=><option value={x.id} key={x.id}>{x.title}</option>)}</select>
 {c?<><button className={button} disabled={busy} onClick={()=>run(async()=>{await api('/api/admin/collaborations',{action:'retention',campaignId:c.id});})}>Limpiar archivos no seleccionados después de 90 días</button><details className="rounded-3xl border border-white/15 p-6" open={c.status==='draft'}><summary className="cursor-pointer text-xl text-gold">Configuración y bases · {c.status}</summary><p className="mt-3 text-sm text-amber-200">Pendiente: {campaignBlockers(c).join(' · ')||'Bases completas'}</p><p className="mt-2 text-xs text-white/50">Límite del módulo: 100 MB en total; pausa cargas si el almacenamiento global supera 900 MB. No activa upgrades. Las fechas se editan en tu hora local y se guardan con zona horaria.</p><form key={c.rules_version} onSubmit={saveCampaign} className="mt-5 grid gap-4 md:grid-cols-2">{[['title','Título'],['description','Descripción'],['project_artist','Artista principal del proyecto'],['legal_entity','Entidad legal vigente'],['eligibility','Territorios y requisitos de elegibilidad'],['promotion_commitment','Piezas y publicaciones de promoción incluidas']].map(([key,label])=><label className="text-sm text-white/65" key={key}>{label}<input name={key} className={input+' mt-2'} defaultValue={(c as any)[key]}/></label>)}{['submissions_start','submissions_end','voting_start','voting_end'].map(key=>{const d=(c as any)[key]?new Date((c as any)[key]):null;const local=d?new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16):'';return <label className="text-sm text-white/65" key={key}>{({submissions_start:'Abre recepción',submissions_end:'Cierra recepción',voting_start:'Abre votación',voting_end:'Cierra votación'} as any)[key]}<input name={key} type="datetime-local" className={input+' mt-2'} defaultValue={local}/></label>;})}<label className="text-sm text-white/65">Máximo de demos<input name="max_submissions" type="number" min={5} max={50} className={input+' mt-2'} defaultValue={c.max_submissions}/></label><label className="text-sm text-white/65">Etapa<select className={input+' mt-2'} name="status" defaultValue={c.status}>{['draft','submissions','voting','closed','production','released'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-white/65 md:col-span-2"><input name="legal_reviewed" type="checkbox" defaultChecked={c.legal_reviewed}/> Las bases y contratos fueron revisados; entidad, territorios y obligaciones están confirmados.</label><button disabled={busy} className={button}>Guardar convocatoria</button></form></details>
 <details className="rounded-3xl border border-white/15 p-6"><summary className="cursor-pointer text-xl text-gold">Beats de esta convocatoria</summary><div className="mt-4 space-y-3">{data.beats.filter((b:any)=>b.campaign_id===c.id).map((b:any)=><p className="text-sm text-white/65" key={b.id}>{b.title} · {b.producer} · {b.rights_confirmed?'Derechos confirmados':'Pendiente'} · {b.license_notes}</p>)}</div><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('/api/admin/collaborations',{action:'beat',campaignId:c.id,sourceId:f.get('source'),producer:f.get('producer'),notes:f.get('notes'),rights:f.get('rights')==='on'});});}}><select name="source" className={input} required aria-label="Beat existente"><option value="">Seleccionar del catálogo existente</option>{data.catalog.map((b:any)=><option key={b.id} value={b.id}>{b.title} · {b.status}</option>)}</select><input name="producer" className={input} required placeholder="Productor titular" aria-label="Productor"/><textarea name="notes" className={input} required placeholder="Evidencia de titularidad, licencias previas, samples, permisos y reserva/exclusividad" aria-label="Permisos del beat"/><label className="block text-sm text-white/65"><input name="rights" type="checkbox" required/> Verifiqué autorización suficiente para esta convocatoria.</label><button className={button} disabled={busy||c.status!=='draft'}>Incluir beat</button></form></details>
 {c.status==='closed'?<details className="rounded-3xl border border-gold/30 p-6"><summary className="cursor-pointer text-gold">Ranking y selección de cinco</summary><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('/api/admin/collaborations',{action:'select',campaignId:c.id,winners:f.getAll('winner'),reserves:f.getAll('reserve'),reason:f.get('reason')||''});});}}>{ranked.map(s=><div className="flex flex-wrap gap-4 text-sm text-white/70" key={s.id}><span>{s.votes} votos · {s.track_title} — {s.artist_name}</span><label><input name="winner" value={s.id} type="checkbox"/> Seleccionado</label><label><input name="reserve" value={s.id} type="checkbox"/> Suplente</label></div>)}<textarea name="reason" className={input} placeholder="Justificación y evidencia del desempate, si aplica"/><button className={button} disabled={busy}>Confirmar cinco y hasta dos suplentes</button></form></details>:null}
 <select className={input} aria-label="Filtrar expedientes" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','received','rights_pending','approved','selected','reserve','rejected','production','released','uploading'].map(x=><option key={x} value={x}>{x==='all'?'Todos los expedientes':x}</option>)}</select><div className="space-y-4">{songs.filter((s:any)=>filter==='all'||s.status===filter).map((s:any)=><SubmissionCard key={s.id+JSON.stringify(s)} s={s} c={c} run={run}/>)}</div>{!songs.length?<p className="text-white/50">Aún no hay demos de esta convocatoria.</p>:null}
 </>:null}<details className="rounded-2xl border border-white/15 p-5"><summary className="cursor-pointer text-gold">Registro de actividad</summary><div className="mt-4 space-y-2">{data.audit.map((a:any)=><p className="text-xs text-white/55" key={a.id}>{a.created_at} · {a.action} · {JSON.stringify(a.details)}</p>)}</div></details></div>;
}
