'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {SUBMISSION_TERMS,MAX_DEMO_BYTES,type Campaign} from '@/lib/collaborations/contracts';
import {api,directUpload,FilePlayer,input,button,downloadText} from './shared';
export function PublicHub({initial}:{initial:any}){
 const [data,setData]=useState(initial),[user,setUser]=useState<any>(null),[mine,setMine]=useState<any>({submissions:[],votes:[]}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[source,setSource]=useState('catalog');
 const [campaignId,setCampaignId]=useState(initial.campaigns[0]?.id||'');const c:Campaign|undefined=data.campaigns.find((x:any)=>x.id===campaignId);
 async function refresh(){const db=createClient();const {data:{user:u}}=await db.auth.getUser();setUser(u);setData(await api('/api/collaborations'));if(u?.email_confirmed_at)setMine(await api('/api/collaborations?kind=mine'));}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message));},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await refresh();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function auth(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const db=createClient();const credentials={email:String(f.get('email')),password:String(f.get('password'))};const r=f.get('mode')==='signup'?await db.auth.signUp({...credentials,options:{emailRedirectTo:location.origin+'/auth/callback'}}):await db.auth.signInWithPassword(credentials);if(r.error)throw r.error;setMessage(f.get('mode')==='signup'?'Revisa tu correo para confirmar la cuenta.':'Sesión iniciada.');});}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await run(async()=>{const file=f.get('demo') as File;if(!file?.size||file.size>MAX_DEMO_BYTES||!file.name.toLowerCase().endsWith('.mp3'))throw new Error('Sube un MP3 de hasta 5 MB.');const pdf=f.get('document') as File;if(source==='external' && (!pdf?.size||pdf.size>2*1024*1024))throw new Error('Adjunta licencia o cesión en PDF, hasta 2 MB.');const x=await api('/api/collaborations',{action:'submit',campaignId,rulesVersion:c!.rules_version,artist_name:f.get('artist_name'),legal_name:f.get('legal_name'),track_title:f.get('track_title'),pro:f.get('pro'),ipi:f.get('ipi'),publisher:f.get('publisher'),publisher_ipi:f.get('publisher_ipi')||'',message:f.get('message')||'',beat_source:source,beat_id:source==='catalog'?f.get('beat_id'):undefined,beat_rights:f.get('beat_rights')||'',preview_consent:f.get('preview')==='on',adult:f.get('adult')==='on',terms:f.get('terms')==='on',bytes:file.size});await directUpload(file,x);await api('/api/collaborations',{action:'complete',id:x.id,uploadId:x.uploadId});if(pdf?.size){const token=await api('/api/collaborations',{action:'document',id:x.id,bytes:pdf.size});await directUpload(pdf,token);await api('/api/collaborations',{action:'complete',id:x.id,uploadId:token.uploadId});}form.reset();setMessage('Demo recibida. El audio completo queda privado para administración.');});}
 return <div className="space-y-10">
 <header><p className="text-xs uppercase tracking-[.25em] text-gold">EM Records × RBELD</p><h1 className="mt-3 font-display text-5xl text-white">Collaborations</h1><p className="mt-4 max-w-2xl text-white/65">Tu canción. Nuestra producción. La comunidad elige cinco temas para el próximo proyecto.</p><div className="mt-5 flex flex-wrap gap-3 text-xs text-gold"><span>50 / 50</span><span>Participación gratuita</span><span>Demos privados</span><span>Cobro individual</span></div></header>
 {message?<p role="status" className="rounded-xl border border-gold/30 p-4 text-sm text-white">{message}</p>:null}
 {data.campaigns.length>1?<select aria-label="Convocatoria" className={input} value={campaignId} onChange={e=>setCampaignId(e.target.value)}>{data.campaigns.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select>:null}
 {c?<section className="rounded-3xl border border-gold/25 bg-white/[.025] p-6"><p className="text-xs uppercase text-gold">{c.status==='draft'?'Próximamente':c.status}</p><h2 className="mt-2 font-display text-3xl text-white">{c.title}</h2><p className="mt-3 text-white/65">{c.description}</p><p className="mt-3 text-sm text-white/50">{c.status==='draft'?'La convocatoria se abrirá cuando se publiquen las bases y fechas definitivas.':`Recepción: ${c.submissions_start} — ${c.submissions_end}. Votación: ${c.voting_start} — ${c.voting_end}.`}</p>
 <details className="mt-5 text-sm text-white/70"><summary className="cursor-pointer text-gold">Bases, derechos y privacidad</summary><div className="mt-4 space-y-3"><p>Organizador: {c.legal_entity||'Por confirmar antes de abrir'}. Elegibilidad: {c.eligibility||'Por definir'}.</p><p>Proyecto: {c.project_artist}. Cinco seleccionados por votos válidos, dos suplentes. Hasta cinco votos por cuenta verificada, uno por canción. No se permiten bots, compra de votos o identidades múltiples.</p><p>Desempate: {String(c.rules.tie_break||'')}</p><p>50% del lado EM y 50% del lado artista en el master final e ingresos, durante la vigencia legal de los derechos. Sin recuperación previa de nuestros aportes. Composición según autores y derechos existentes; acuerdo separado firmado. No obliga a entregar otras canciones.</p><p>Aportes: {String(c.rules.included||'')}. Promoción: {c.promotion_commitment||'Se publicará antes de abrir'}.</p><p>Cada beneficiario necesita cuenta habilitada para cobrar Splits y asume los costos de su cuenta y retiro según el contrato. Estar afiliado a un PRO y declarar publishing/administración es requisito del proyecto, no una obligación legal universal.</p><p>{SUBMISSION_TERMS}</p><p>Contacto, retiros, privacidad e incidencias: <a className="text-gold" href="mailto:emrecordsllc@gmail.com">emrecordsllc@gmail.com</a>. Puedes solicitar acceso, corrección o eliminación de tus datos sujeto a conservación legal. Sin cinco temas elegibles se informará cancelación o nueva convocatoria; no se prometen plazas a temas no elegibles.</p><p>Versión de bases: {c.rules_version}. Las condiciones definitivas están disponibles antes del envío.</p></div></details></section>:<p>No hay convocatorias disponibles.</p>}
 {!user?<section className="rounded-3xl border border-white/15 p-6"><h2 className="text-xl text-white">Entra para enviar o votar</h2><form onSubmit={auth} className="mt-4 grid gap-3 sm:grid-cols-2"><input className={input} name="email" type="email" required placeholder="Correo electrónico" aria-label="Correo"/><input className={input} name="password" type="password" required minLength={8} placeholder="Contraseña" aria-label="Contraseña"/><select name="mode" className={input} aria-label="Acción de cuenta"><option value="login">Entrar con mi cuenta</option><option value="signup">Crear cuenta gratuita</option></select><button className={button} disabled={busy}>Continuar</button></form></section>:<p className="text-sm text-white/60">Sesión: {user.email} · <button className="text-gold" onClick={()=>run(async()=>{await createClient().auth.signOut();setMine({submissions:[],votes:[]});})}>Salir</button>{!user.email_confirmed_at?' · Confirma tu correo antes de participar.':''}</p>}
 {user?.email_confirmed_at && c?.status==='submissions'?<section><h2 className="font-display text-3xl text-white">Envía tu demo</h2><form onSubmit={submit} className="mt-5 grid gap-4 rounded-3xl border border-white/15 p-6 md:grid-cols-2">{[['artist_name','Nombre artístico'],['legal_name','Nombre legal'],['track_title','Título'],['pro','PRO (BMI, ASCAP, etc.)'],['ipi','IPI / CAE del compositor'],['publisher','Publisher o administración propia'],['publisher_ipi','IPI del publisher, si existe']].map(([name,label])=><label key={name} className="text-sm text-white/65">{label}<input className={input+' mt-2'} name={name} required={name!=='publisher_ipi'} maxLength={200}/></label>)}
 <label className="text-sm text-white/65">Origen del beat<select className={input+' mt-2'} value={source} onChange={e=>setSource(e.target.value)}><option value="catalog">Catálogo EM Records</option><option value="external">Beat propio o licenciado</option></select></label>
 {source==='catalog'?<label className="text-sm text-white/65">Beat aprobado<select className={input+' mt-2'} name="beat_id" required><option value="">Selecciona</option>{data.beats.filter((b:any)=>b.campaign_id===campaignId).map((b:any)=><option value={b.id} key={b.id}>{b.title} — {b.producer}</option>)}</select><Link href="/beats" className="mt-2 inline-block text-gold" target="_blank">Escuchar catálogo</Link></label>:<label className="text-sm text-white/65">Propiedad o licencia<textarea name="beat_rights" className={input+' mt-2'} required maxLength={3000} placeholder="Productor, titular, licencia, samples y restricciones"/></label>}
 <label className="text-sm text-white/65">Demo MP3, hasta 5 MB<input className={input+' mt-2'} type="file" name="demo" accept="audio/mpeg,.mp3" required/></label><label className="text-sm text-white/65">Licencia / cesión PDF, hasta 2 MB<input className={input+' mt-2'} type="file" name="document" accept="application/pdf" required={source==='external'}/></label><textarea name="message" className={input+' md:col-span-2'} maxLength={2000} placeholder="Tu propuesta" aria-label="Propuesta"/>
 <div className="space-y-3 text-sm text-white/70 md:col-span-2"><label className="block"><input type="checkbox" name="adult" required/> Tengo 18 años o más y cumplo la elegibilidad.</label><label className="block"><input type="checkbox" name="terms" required/> Leí y acepto las bases, el permiso de revisión y la privacidad.</label><label className="block"><input type="checkbox" name="preview" required/> Autorizo publicar el preview de hasta 30 segundos según el permiso anterior.</label></div><button className={button} disabled={busy}>{busy?'Enviando…':'Enviar demo privado'}</button></form></section>:null}
 <section><h2 className="font-display text-3xl text-white">Escucha y vota</h2><p className="mt-2 text-sm text-white/55">Solo previews. Los conteos permanecen privados hasta el cierre.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{data.tracks.filter((s:any)=>s.campaign_id===campaignId).map((s:any)=><article key={s.id} className="rounded-2xl border border-white/15 p-5"><h3 className="text-xl text-white">{s.track_title}</h3><p className="mb-4 text-sm text-white/55">{s.artist_name}</p><FilePlayer id={s.id}/>{c?.status==='voting'?<button disabled={busy||mine.votes.some((v:any)=>v.submission_id===s.id)} className={button+' mt-4'} onClick={()=>run(async()=>{await api('/api/collaborations',{action:'vote',id:s.id});setMessage('Voto registrado.');})}>{mine.votes.some((v:any)=>v.submission_id===s.id)?'Votaste por este tema':'Votar'}</button>:null}{['selected','production','released'].includes(s.status)?<p className="mt-3 text-gold">Seleccionado</p>:null}</article>)}</div>{!data.tracks.some((s:any)=>s.campaign_id===campaignId)?<p className="mt-5 text-white/50">Los previews aparecerán cuando se abra la votación.</p>:null}</section>
 {mine.submissions.length?<section><h2 className="font-display text-3xl text-white">Mis expedientes</h2><div className="mt-4 space-y-4">{mine.submissions.map((s:any)=><article className="rounded-2xl border border-white/15 p-5" key={s.id}><h3 className="text-xl text-white">{s.track_title}</h3><p className="text-sm text-gold">{s.status}</p>{s.status==='uploading'?<label className="mt-3 block text-sm text-amber-200">Completar carga del MP3 original<input type="file" accept="audio/mpeg,.mp3" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)run(async()=>{const t=await api('/api/collaborations',{action:'resume',id:s.id,bytes:f.size});if(!t.alreadyUploaded)await directUpload(f,t);await api('/api/collaborations',{action:'complete',id:s.id,uploadId:t.uploadId});setMessage('Carga completada.');});}}/></label>:null}<label className="mt-3 block text-sm text-white/65">Adjuntar permiso PDF<input type="file" accept="application/pdf" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)run(async()=>{const t=await api('/api/collaborations',{action:'document',id:s.id,bytes:f.size});await directUpload(f,t);await api('/api/collaborations',{action:'complete',id:s.id,uploadId:t.uploadId});setMessage('Documento adjuntado.');});}}/></label>{s.contract_ready?<details className="mt-4"><summary className="cursor-pointer text-gold">Acuerdo y anexos</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap text-sm text-white/70">{s.contract_text}</pre><button className={button+' mt-3'} onClick={()=>downloadText(`${s.track_title}-acuerdo.txt`,s.contract_text)}>Descargar copia</button>{s.contract_signature?<p className="mt-3 text-emerald-300">Aceptado: {s.contract_signature.accepted_at}. Pendiente de verificar las demás firmas.</p>:<form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('/api/collaborations',{action:'accept_contract',id:s.id,hash:s.contract_hash,name:f.get('name'),consent:f.get('consent')==='on'});setMessage('Aceptación registrada.');});}}><input name="name" className={input} required placeholder="Tu nombre legal exacto" aria-label="Nombre para aceptación"/><label className="block text-sm text-white/70"><input name="consent" type="checkbox" required/> Leí el acuerdo y acepto firmar electrónicamente mediante mi cuenta y nombre legal.</label><button className={button} disabled={busy}>Aceptar acuerdo</button></form>}</details>:null}</article>)}</div></section>:null}
 </div>;
}
