import { EM_RECORDS_DEFAULT_LEGAL_ENTITY } from "@/lib/signing/constants";

export const OFFICIAL_RECORDING_AGREEMENT_TEMPLATE_NAME = "EM Records Artist Recording Agreement";
export const OFFICIAL_RECORDING_AGREEMENT_TEMPLATE_VERSION = "v2.1";
export const OFFICIAL_RECORDING_AGREEMENT_LANGUAGE_OPTIONS = ["en", "es"] as const;

export type RecordingAgreementLanguage = (typeof OFFICIAL_RECORDING_AGREEMENT_LANGUAGE_OPTIONS)[number];

export const OFFICIAL_RECORDING_AGREEMENT_CLAUSE_SCHEMA = {
  includes_publishing: false,
  includes_360: true,
  perpetual_master_rights: true
} as const;

export const OFFICIAL_RECORDING_AGREEMENT_DEFAULT_VARIABLES = {
  agreement_day: "___",
  agreement_month: "__________________________",
  agreement_year: "20__",
  contract_language: "en",
  label_legal_entity: EM_RECORDS_DEFAULT_LEGAL_ENTITY,
  label_principal_place_of_business: "State of Texas, United States",
  artist_legal_name: "__________________________",
  artist_stage_name: "__________________________",
  initial_term_commitment: "Three (3) Commercial Singles",
  initial_term_period: "Twelve (12) months",
  extension_option_description: "Two (2) additional Singles OR one (1) EP project",
  royalty_split_label: "50",
  royalty_split_artist: "50",
  optional_360_cap: "20% of net income",
  live_split_artist: "70",
  live_split_label: "30",
  anti_bypass_term: "two (2) years following termination",
  royalty_statement_frequency: "semi-annually",
  royalty_payment_window: "45 days",
  governing_law: "State of Texas, United States",
  label_signer_name: "",
  label_signer_title: "",
  label_signature_date: "",
  artist_signature_date: ""
} as const;

const OFFICIAL_RECORDING_AGREEMENT_BODY_MARKDOWN_EN = `# EM RECORDS
## ARTIST RECORDING AGREEMENT

This Artist Recording Agreement ("Agreement") is made effective as of {{effective_date}}.

Between:

{{label_legal_entity}}, a limited liability company organized under the laws of the State of Texas, United States (hereinafter referred to as the "Label")

and

{{artist_legal_name}}, professionally known as {{artist_stage_name}} (hereinafter referred to as the "Artist").

Collectively referred to as the "Parties."

## DEFINITIONS

Masters
Sound recordings created under this Agreement.

Net Income
Gross revenue received by the Label minus recoupable expenses.

Recoupable Expenses
All costs advanced by the Label in connection with the Artist including production, marketing, promotion, videos, artwork and distribution.

Territory
Worldwide.

## TERM

The initial term shall consist of:
- {{initial_term_commitment}}
- OR
- {{initial_term_period}}, whichever occurs first.

The Label shall have the exclusive option to extend the Agreement for:
- {{extension_option_description}}

## DELIVERY REQUIREMENTS

The Artist shall deliver to the Label:
- Fully recorded vocals
- Promotional content
- Cooperation for video and marketing

The Label shall determine final approval of all Masters.

## EXCLUSIVITY

During the term of this Agreement the Artist shall not:
- Record for another label
- Release commercial music independently
- Sign distribution agreements
- License music without Label approval

All recordings made during the term related to the Artist brand shall be delivered exclusively to the Label.

## LABEL SERVICES

The Label may provide:
- Music production
- Recording studio access
- Mixing and mastering
- Video production
- Photography
- Branding and image development
- Digital distribution
- Marketing campaigns
- Strategic artist development

## INVESTMENT AND RECOUPMENT

All Label investments shall be recoupable from revenue generated by the Masters.

Recoupable costs include but are not limited to:
- Beat production
- Studio sessions
- Mixing and mastering
- Video production
- Photography
- Marketing and advertising
- Artwork
- Distribution costs
- Travel expenses
- Creative direction

The Label shall recoup 100% of these costs before profit participation is calculated.

## REVENUE PARTICIPATION

After recoupment:
- {{royalty_split_artist}}% - Artist
- {{royalty_split_label}}% - {{label_legal_entity}}

Revenue sources include:
- Streaming income
- Music downloads
- YouTube monetization
- Sync licensing
- Social media monetization
- Master related merchandise

## MASTER OWNERSHIP

All Masters created under this Agreement shall be the sole and exclusive property of {{label_legal_entity}} [if:perpetual_master_rights]in perpetuity[/if:perpetual_master_rights].

The Artist acknowledges the recordings are considered work made for hire.

If not legally considered work for hire, the Artist irrevocably assigns all rights to the Label.

## WORLDWIDE EXPLOITATION

The Label shall have exclusive rights to exploit the Masters worldwide including:
- Streaming platforms
- Digital downloads
- Radio
- Television
- Film
- Video games
- Social media platforms
- Advertising campaigns
- Emerging technologies

The Label may sublicense such rights to third parties.

## NAME AND LIKENESS RIGHTS

The Artist grants the Label the right to use:
- Artist name
- Image
- Likeness
- Voice
- Biography
- Photographs

for promotional and commercial purposes related to the Masters.

## AUDIOVISUAL CONTENT

All audiovisual content produced by the Label including:
- Music videos
- Visualizers
- Promotional footage
- Social media content

shall be owned exclusively by {{label_legal_entity}}.

## SYNC LICENSING

The Label shall have exclusive authority to negotiate synchronization licenses including:
- Film
- Television
- Commercials
- Video games
- Streaming platforms

[if:includes_publishing]
## PUBLISHING

Publishing participation, if approved by the Label in writing, shall be allocated according to actual songwriting contributions and applicable split sheets.
[/if:includes_publishing]

[if:includes_360]
## OPTIONAL 360 PARTICIPATION

During the term of this Agreement the Label may participate in the Artist's non-recording income including:
- Live performances
- Tours
- Merchandise
- Sponsorships
- Brand partnerships
- Influencer campaigns

Participation shall not exceed {{optional_360_cap}} and applies only when the opportunity is generated by the Label.
[/if:includes_360]

## LIVE PERFORMANCES

Unless otherwise agreed:
- {{live_split_artist}}% Artist
- {{live_split_label}}% Label

If the Label finances or produces the event the percentages may be renegotiated.

## MERCHANDISE

Merchandise created in connection with Label releases may be jointly owned.

Revenue split shall be negotiated per project.

## CONFIDENTIALITY

The Artist agrees not to disclose:
- Financial terms
- Label strategies
- Business contacts
- Contract terms

without Label consent.

## ANTI-BYPASS

The Artist shall not circumvent the Label in any deals related to their music career during the term and {{anti_bypass_term}}.

## ROYALTY ACCOUNTING

Royalty statements shall be issued {{royalty_statement_frequency}}.

Payments shall be made within {{royalty_payment_window}} of statement delivery.

The Artist may audit Label records once per year.

## MORALITY CLAUSE

If the Artist engages in conduct that materially damages the reputation of the Label, the Label may suspend or terminate the Agreement.

## TERMINATION

The Label may terminate this Agreement if the Artist:
- Breaches contractual obligations
- Fails to attend sessions
- Violates exclusivity
- Engages in conduct damaging to the Label

Termination shall not affect Label ownership of Masters.

## GOVERNING LAW

This Agreement shall be governed by the laws of the {{governing_law}}.

## DISPUTE RESOLUTION

Disputes shall be resolved through:
1. Negotiation
2. Mediation
3. Binding arbitration

before litigation.

## ENTIRE AGREEMENT

This document represents the entire agreement between the Parties.

## SIGNATURES

{{label_legal_entity}}

By: __________________________
Name: {{label_signer_name}}
Title: {{label_signer_title}}
Date: {{label_signature_date}}

ARTIST

Legal Name: {{artist_legal_name}}
Artist Name: {{artist_stage_name}}
Signature: Completed electronically through the EM Records signing portal.
Date: {{artist_signature_date}}`;

const OFFICIAL_RECORDING_AGREEMENT_BODY_MARKDOWN_ES = `# EM RECORDS
## CONTRATO DE GRABACION ARTISTICA

El presente Contrato de Grabacion Artistica ("Contrato") entra en vigor el {{effective_date}}.

Entre:

{{label_legal_entity}}, una sociedad de responsabilidad limitada organizada conforme a las leyes del Estado de Texas, Estados Unidos (en adelante, el "Sello")

y

{{artist_legal_name}}, profesionalmente conocido como {{artist_stage_name}} (en adelante, el "Artista").

Conjuntamente denominados las "Partes".

## DEFINICIONES

Masters
Grabaciones sonoras creadas bajo este Contrato.

Ingreso Neto
Ingreso bruto recibido por el Sello menos gastos recuperables.

Gastos Recuperables
Todos los costos adelantados por el Sello en relacion con el Artista, incluyendo produccion, marketing, promocion, videos, arte y distribucion.

Territorio
Mundial.

## PLAZO

El plazo inicial consistira en:
- {{initial_term_commitment}}
- O
- {{initial_term_period}}, lo que ocurra primero.

El Sello tendra la opcion exclusiva de extender el Contrato por:
- {{extension_option_description}}

## REQUISITOS DE ENTREGA

El Artista entregara al Sello:
- Voces completamente grabadas
- Contenido promocional
- Cooperacion para video y marketing

El Sello determinara la aprobacion final de todos los Masters.

## EXCLUSIVIDAD

Durante la vigencia de este Contrato, el Artista no podra:
- Grabar para otro sello
- Lanzar musica comercial de forma independiente
- Firmar acuerdos de distribucion
- Licenciar musica sin aprobacion del Sello

Todas las grabaciones realizadas durante la vigencia del Contrato relacionadas con la marca del Artista seran entregadas exclusivamente al Sello.

## SERVICIOS DEL SELLO

El Sello podra proporcionar:
- Produccion musical
- Acceso a estudio de grabacion
- Mezcla y masterizacion
- Produccion de video
- Fotografia
- Branding y desarrollo de imagen
- Distribucion digital
- Campanas de marketing
- Desarrollo estrategico del artista

## INVERSION Y RECUPERACION

Todas las inversiones del Sello seran recuperables de los ingresos generados por los Masters.

Los costos recuperables incluyen, entre otros:
- Produccion de beats
- Sesiones de estudio
- Mezcla y masterizacion
- Produccion de video
- Fotografia
- Marketing y publicidad
- Arte grafico
- Costos de distribucion
- Gastos de viaje
- Direccion creativa

El Sello recuperara el 100% de estos costos antes de calcular la participacion en beneficios.

## PARTICIPACION EN INGRESOS

Despues de la recuperacion:
- {{royalty_split_artist}}% Artista
- {{royalty_split_label}}% {{label_legal_entity}}

Las fuentes de ingresos incluyen:
- Ingreso por streaming
- Descargas musicales
- Monetizacion en YouTube
- Licencias de sincronizacion
- Monetizacion en redes sociales
- Mercancia relacionada con los Masters

## PROPIEDAD DE LOS MASTERS

Todos los Masters creados bajo este Contrato seran propiedad unica y exclusiva de {{label_legal_entity}} [if:perpetual_master_rights]a perpetuidad[/if:perpetual_master_rights].

El Artista reconoce que las grabaciones se consideran work made for hire.

Si legalmente no se consideran work made for hire, el Artista cede irrevocablemente todos los derechos al Sello.

## EXPLOTACION MUNDIAL

El Sello tendra derechos exclusivos para explotar los Masters en todo el mundo, incluyendo:
- Plataformas de streaming
- Descargas digitales
- Radio
- Television
- Cine
- Videojuegos
- Plataformas de redes sociales
- Campanas publicitarias
- Tecnologias emergentes

El Sello podra sublicenciar dichos derechos a terceros.

## DERECHOS DE NOMBRE E IMAGEN

El Artista concede al Sello el derecho de utilizar:
- Nombre artistico
- Imagen
- Likeness
- Voz
- Biografia
- Fotografias

para fines promocionales y comerciales relacionados con los Masters.

## CONTENIDO AUDIOVISUAL

Todo contenido audiovisual producido por el Sello, incluyendo:
- Videos musicales
- Visualizers
- Material promocional
- Contenido para redes sociales

sera propiedad exclusiva de {{label_legal_entity}}.

## LICENCIAS DE SINCRONIZACION

El Sello tendra autoridad exclusiva para negociar licencias de sincronizacion, incluyendo:
- Cine
- Television
- Comerciales
- Videojuegos
- Plataformas de streaming

[if:includes_publishing]
## EDICION

La participacion editorial, si es aprobada por escrito por el Sello, se asignara segun las contribuciones reales de composicion y las hojas de reparto aplicables.
[/if:includes_publishing]

[if:includes_360]
## PARTICIPACION 360 OPCIONAL

Durante la vigencia de este Contrato, el Sello podra participar en ingresos no fonograficos del Artista, incluyendo:
- Presentaciones en vivo
- Giras
- Mercancia
- Patrocinios
- Alianzas de marca
- Campanas con influencers

La participacion no excedera {{optional_360_cap}} y aplicara solo cuando la oportunidad haya sido generada por el Sello.
[/if:includes_360]

## PRESENTACIONES EN VIVO

Salvo pacto distinto:
- {{live_split_artist}}% Artista
- {{live_split_label}}% Sello

Si el Sello financia o produce el evento, los porcentajes podran renegociarse.

## MERCANCIA

La mercancia creada en relacion con lanzamientos del Sello podra ser de propiedad conjunta.

La division de ingresos se negociara por proyecto.

## CONFIDENCIALIDAD

El Artista acepta no divulgar:
- Terminos financieros
- Estrategias del Sello
- Contactos comerciales
- Terminos contractuales

sin el consentimiento del Sello.

## ANTI-BYPASS

El Artista no podra eludir al Sello en ningun acuerdo relacionado con su carrera musical durante la vigencia del Contrato y {{anti_bypass_term}}.

## LIQUIDACION DE REGALIAS

Los estados de regalias se emitiran {{royalty_statement_frequency}}.

Los pagos se realizaran dentro de {{royalty_payment_window}} de la entrega del estado.

El Artista podra auditar los registros del Sello una vez por ano.

## CLAUSULA MORAL

Si el Artista incurre en una conducta que dañe materialmente la reputacion del Sello, el Sello podra suspender o terminar el Contrato.

## TERMINACION

El Sello podra terminar este Contrato si el Artista:
- Incumple obligaciones contractuales
- No asiste a sesiones
- Viola la exclusividad
- Participa en conductas que dañen al Sello

La terminacion no afectara la propiedad del Sello sobre los Masters.

## LEY APLICABLE

Este Contrato se regira por las leyes de {{governing_law}}.

## RESOLUCION DE DISPUTAS

Las disputas se resolveran mediante:
1. Negociacion
2. Mediacion
3. Arbitraje vinculante

antes de litigio.

## ACUERDO INTEGRO

Este documento representa el acuerdo integro entre las Partes.

## FIRMAS

{{label_legal_entity}}

Por: __________________________
Nombre: {{label_signer_name}}
Cargo: {{label_signer_title}}
Fecha: {{label_signature_date}}

ARTISTA

Nombre legal: {{artist_legal_name}}
Nombre artistico: {{artist_stage_name}}
Firma: Completada electronicamente a traves del portal de firma de EM Records.
Fecha: {{artist_signature_date}}`;

export const OFFICIAL_RECORDING_AGREEMENT_BODY_MARKDOWN = OFFICIAL_RECORDING_AGREEMENT_BODY_MARKDOWN_EN;

export function normalizeRecordingAgreementLanguage(value: string | null | undefined): RecordingAgreementLanguage {
  const normalized = String(value ?? "").trim().toLowerCase();
  return normalized.startsWith("es") ? "es" : "en";
}

export function resolveOfficialRecordingAgreementTitle(language: string | null | undefined): string {
  return normalizeRecordingAgreementLanguage(language) === "es" ? "Contrato de Grabacion Artistica" : "Artist Recording Agreement";
}

export function resolveOfficialRecordingAgreementMarkdown(language: string | null | undefined): string {
  return normalizeRecordingAgreementLanguage(language) === "es"
    ? OFFICIAL_RECORDING_AGREEMENT_BODY_MARKDOWN_ES
    : OFFICIAL_RECORDING_AGREEMENT_BODY_MARKDOWN_EN;
}
