do $$
begin
  if to_regclass('public.contract_templates') is null then
    raise notice 'Skipping artist recording agreement template migration because public.contract_templates does not exist yet.';
    return;
  end if;

  update public.contract_templates
  set active = false
  where name = 'EM Records 50/50 Artist Deal';

  insert into public.contract_templates (
    name,
    version_name,
    body_markdown,
    clause_schema,
    default_variables,
    active
  )
  values (
    'EM Records Artist Recording Agreement',
    'v2.0',
    $template$
# ARTIST RECORDING AGREEMENT
## EM RECORDS LLC

This Artist Recording Agreement ("Agreement") is entered into effective {{effective_date}}.

Between:

{{label_legal_entity}}, a limited liability company organized under the laws of the United States, with principal place of business determined by the Label at {{label_principal_place_of_business}} (hereinafter referred to as "Label")

and

{{artist_legal_name}}, professionally known as {{artist_stage_name}} (hereinafter referred to as "Artist").

The Label and the Artist may collectively be referred to as the "Parties."

## PURPOSE OF AGREEMENT

The Artist hereby grants to the Label the exclusive right to:
- Produce
- Record
- Manufacture
- Distribute
- Market
- Promote
- License
- Monetize

musical recordings performed by the Artist during the term of this Agreement.

Such recordings shall be referred to as "Masters" or "Master Recordings."

## TERM

The initial term of this Agreement shall consist of:
- {{initial_term_commitment}}
- OR
- {{initial_term_period}}, whichever occurs first.

The Label shall have the exclusive option to extend the Agreement for:
- {{extension_option_description}}

The extension option must be exercised by the Label in writing.

## EXCLUSIVITY

During the term of this Agreement the Artist agrees that they shall not:
- Record for another record label
- Release music commercially without Label approval
- Enter distribution agreements with third parties
- License music independently

without the prior written consent of {{label_legal_entity}}.

The Artist agrees that all recordings created during the term related to the Artist brand will be delivered to the Label.

## LABEL RESPONSIBILITIES

The Label agrees to provide professional development and production services which may include:
- Music production
- Studio recording sessions
- Mixing and mastering
- Video production
- Photography and branding
- Marketing and promotion
- Digital distribution
- Content creation
- Strategic career guidance

The scope of these services may vary per project.

## INVESTMENT AND RECOUPMENT

All expenses incurred by the Label in connection with the Artist shall be deemed recoupable costs.

Such expenses may include but are not limited to:
- Music production
- Beat licensing or creation
- Recording sessions
- Mixing and mastering
- Video production
- Photography
- Marketing campaigns
- Promotion
- Advertising
- Distribution fees
- Travel related to production
- Creative direction
- Artwork creation

The Label shall be entitled to recoup 100% of its investment from gross revenues generated by the Masters before profit participation is calculated.

## REVENUE SPLIT

After recoupment of all Label investments, net income derived from the Masters shall be split as follows:
- {{royalty_split_artist}}% - Artist
- {{royalty_split_label}}% - {{label_legal_entity}}

Income sources include but are not limited to:
- Digital streaming
- Music downloads
- YouTube monetization
- Licensing
- Synchronization
- Digital platforms
- Social media monetization
- Master-related merchandise

## MASTER OWNERSHIP

All Master Recordings produced under this Agreement shall be the sole and exclusive property of {{label_legal_entity}} [if:perpetual_master_rights]in perpetuity[/if:perpetual_master_rights].

The Artist acknowledges that such recordings constitute work made for hire.

If any Master Recording does not qualify as work for hire under applicable law, the Artist hereby irrevocably assigns all rights, title, and interest in such recordings to the Label.

The Label retains full authority to:
- Distribute
- License
- Sell
- Monetize
- Synchronize
- Exploit

the Masters worldwide without time limitation.

The Artist shall receive only the royalty participation described in this Agreement.

## WORLDWIDE EXPLOITATION

The Artist grants the Label the exclusive worldwide rights to exploit the Masters in all territories and in all formats, whether currently known or developed in the future.

This includes but is not limited to:
- Streaming services
- Digital downloads
- Radio
- Television
- Film
- Social media platforms
- Video games
- Advertising
- Brand licensing
- Emerging technologies

The Label may sublicense these rights to third parties.

[if:includes_publishing]
## PUBLISHING

Publishing rights shall be allocated based on actual songwriting contributions.

Typical structure example:
- Producer / Label contribution
- Artist contribution

Publishing may be registered with:
- BMI
- The MLC
- SoundExchange
- Other performing rights organizations

Song split sheets will determine final percentages.
[/if:includes_publishing]

[if:includes_360]
## OPTIONAL 360 PARTICIPATION

In consideration of the Label's investment in developing the Artist's career, the Label may participate in certain non-recording revenue streams during the term of this Agreement.

Such revenue streams may include:
- Live performances
- Touring
- Merchandise
- Brand sponsorships
- Endorsements
- Public appearances
- Influencer campaigns
- Brand collaborations

The Label participation shall not exceed {{optional_360_cap}} and shall apply only where the opportunity was created, facilitated, or negotiated by the Label.
[/if:includes_360]

## LIVE PERFORMANCES

Unless otherwise agreed in writing, live performance income shall be divided as follows:
- {{live_split_artist}}% - Artist
- {{live_split_label}}% - Label

If the Label organizes or finances a live event, percentages may be adjusted accordingly.

## ARTIST OBLIGATIONS

The Artist agrees to:
- Attend recording sessions
- Participate in promotional content
- Promote releases through social media
- Maintain professional conduct
- Cooperate with Label marketing efforts
- Deliver vocals and recordings on schedule
- Avoid conduct damaging to the Label's reputation

## ANTI-BYPASS / NON-CIRCUMVENTION

The Artist agrees not to bypass, circumvent, or avoid the Label in any business dealings related to the Artist's music career during the term of this Agreement and for a period of {{anti_bypass_term}}.

This includes but is not limited to:
- Negotiating with Label contacts independently
- Entering deals with parties introduced by the Label
- Transferring rights without Label consent

Violation of this clause entitles the Label to:
- Financial damages
- Recovery of lost profits
- Enforcement of its revenue participation

## ROYALTY ACCOUNTING

The Label shall maintain accounting records of income generated from exploitation of the Masters.

Royalty statements shall be issued {{royalty_statement_frequency}}.

Statements shall include:
- Total income
- Recoupable expenses
- Remaining balance
- Artist share

Payments shall be issued within {{royalty_payment_window}}.

The Artist may audit the Label's records once per year with reasonable written notice.

## TERMINATION

The Label may terminate this Agreement if the Artist:
- Breaches contract obligations
- Fails to attend recording sessions
- Damages Label reputation
- Violates exclusivity terms

Termination shall not affect the Label's ownership of Masters created prior to termination.

## INDEPENDENT CONTRACTOR

The Artist shall be considered an independent contractor and not an employee of the Label.

## GOVERNING LAW

This Agreement shall be governed by the laws of the {{governing_law}}.

## DISPUTE RESOLUTION

Any dispute arising under this Agreement shall first be resolved through:
- Good faith negotiation
- Mediation
- Binding arbitration

before litigation.

## ENTIRE AGREEMENT

This document represents the entire agreement between the Parties and supersedes any prior agreements or understandings.

No modification shall be valid unless made in writing and signed by both Parties.

## SIGNATURES

{{label_legal_entity}}

Authorized representative signature: Completed electronically through the EM Records signing portal.

Date: {{label_signature_date}}

ARTIST

Legal Name: {{artist_legal_name}}

Artist Name: {{artist_stage_name}}

Signature: Completed electronically through the EM Records signing portal.

Date: {{artist_signature_date}}
    $template$,
    '{
      "includes_publishing": true,
      "includes_360": false,
      "perpetual_master_rights": true
    }'::jsonb,
    '{
      "agreement_day": "___",
      "agreement_month": "__________________________",
      "agreement_year": "20__",
      "contract_language": "en",
      "label_legal_entity": "EM Records LLC",
      "label_principal_place_of_business": "Austin, Texas",
      "artist_legal_name": "__________________________",
      "artist_stage_name": "__________________________",
      "initial_term_commitment": "Three (3) Commercial Singles",
      "initial_term_period": "Twelve (12) months",
      "extension_option_description": "Two (2) additional Singles OR one (1) EP project.",
      "royalty_split_label": "50",
      "royalty_split_artist": "50",
      "optional_360_cap": "20% of net income",
      "live_split_artist": "70",
      "live_split_label": "30",
      "anti_bypass_term": "two (2) years following termination",
      "royalty_statement_frequency": "every six (6) months",
      "royalty_payment_window": "45 days after statement delivery",
      "governing_law": "State of Texas, United States",
      "label_signer_name": "",
      "label_signer_title": "",
      "label_signature_date": "",
      "artist_signature_date": ""
    }'::jsonb,
    true
  )
  on conflict (name, version_name) do update
  set
    body_markdown = excluded.body_markdown,
    clause_schema = excluded.clause_schema,
    default_variables = excluded.default_variables,
    active = excluded.active;
end
$$;
